### ISSUE TITLE
callback is not a function (webpack v4)

### ISSUE THREAD

**Issue by thescientist13** [arthurbergmz/webpack-pwa-manifest#52]
I've upgraded to the latest version of `webpack@4.0.0` and `webpack-pwa-manifest@3.5.0` and am seeing this error when running my current build
```shell
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
       [3] ../node_modules/html-webpack-plugin/lib/loader.js!./index.html 843 bytes {0} [built]
        + 3 hidden modules
/Users/owenbuckley/Workspace/pvdgeeks.org/website-frontend/node_modules/webpack-pwa-manifest/dist/index.js:72
            callback(null, htmlPluginData);
            ^

TypeError: callback is not a function
    at /Users/owenbuckley/Workspace/pvdgeeks.org/website-frontend/node_modules/webpack-pwa-manifest/dist/index.js:72:13
    at /Users/owenbuckley/Workspace/pvdgeeks.org/website-frontend/node_modules/webpack-pwa-manifest/dist/injector/index.js:96:9
    at manifest (/Users/owenbuckley/Workspace/pvdgeeks.org/website-frontend/node_modules/webpack-pwa-manifest/dist/injector/index.js:76:3)
    at /Users/owenbuckley/Workspace/pvdgeeks.org/website-frontend/node_modules/webpack-pwa-manifest/dist/injector/index.js:92:7
    at processNext (/Users/owenbuckley/Workspace/pvdgeeks.org/website-frontend/node_modules/webpack-pwa-manifest/dist/icons/index.js:107:14)
    at Jimp.<anonymous> (/Users/owenbuckley/Workspace/pvdgeeks.org/website-frontend/node_modules/webpack-pwa-manifest/dist/icons/index.js:134:16)
    at /Users/owenbuckley/Workspace/pvdgeeks.org/website-frontend/node_modules/jimp/index.js:2255:27
    at /Users/owenbuckley/Workspace/pvdgeeks.org/website-frontend/node_modules/stream-to/index.js:39:7
    at exports.PNG.onEnd (/Users/owenbuckley/Workspace/pvdgeeks.org/website-frontend/node_modules/stream-to/index.js:18:5)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at exports.PNG.emit (events.js:208:7)
    at emitNone (events.js:106:13)
    at module.exports.emit (events.js:208:7)
    at module.exports.<anonymous> (/Users/owenbuckley/Workspace/pvdgeeks.org/website-frontend/node_modules/pngjs/lib/packer-async.js:41:10)
    at emitNone (events.js:111:20)
    at Deflate.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Likely this is related to some breaking change?
https://medium.com/webpack/webpack-4-migration-guide-for-plugins-loaders-20a79b927202

You can see [my PR here in my project](https://github.com/ProvidenceGeeks/website-frontend/pull/142) where if you resnable `WebpackPwaManifest` in _webpack.config.prod.js_ and ran `yarn build`, you can reproduce the error.

Is there any plan for an upgrade?  Any pointers for someone to contribute it?  Thanks for the great work on this plugin!  🙏 ✌️

**Comment by frlinw** [comment]
https://github.com/arthurbergmz/webpack-pwa-manifest/issues/44#issuecomment-366456547

should be released today but it can take few more days, be patient

**Comment by thescientist13** [comment]
thanks @frlinw !!

**Comment by arthurbergmz** [comment]
@thescientist13 
Please, update to **v3.6.0** due to Webpack 4 support.

**Comment by thescientist13** [comment]
thanks @arthurbergmz , will give it a go!
