### ISSUE TITLE
tapAsync issue with webpack 4

### ISSUE THREAD

**Issue by fernandopasik** [arthurbergmz/webpack-pwa-manifest#53]
Hi I'm having this issue when I use webpack or webpack-dev-server

```
/asdf/node_modules/webpack-dev-server/bin/webpack-dev-server.js:405
    throw e;
    ^

TypeError: Cannot read property 'tapAsync' of undefined
    at /asdf/node_modules/webpack-pwa-manifest/dist/generators/tapable.js:11:61
    at SyncHook.eval [as call] (eval at create (/asdf/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:17:12), <anonymous>:13:1)
    at SyncHook.lazyCompileHook [as _call] (/asdf/node_modules/webpack/node_modules/tapable/lib/Hook.js:35:21)
    at Compiler.newCompilation (/asdf/node_modules/webpack/lib/Compiler.js:418:26)
    at hooks.beforeCompile.callAsync.err (/asdf/node_modules/webpack/lib/Compiler.js:457:29)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/asdf/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/asdf/node_modules/webpack/node_modules/tapable/lib/Hook.js:35:21)
    at Compiler.compile (/asdf/node_modules/webpack/lib/Compiler.js:452:28)
    at compiler.hooks.watchRun.callAsync.err (/asdf/node_modules/webpack/lib/Watching.js:77:18)
    at _err0 (eval at create (/asdf/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:11:1)
    at invalid (/asdf/node_modules/webpack-dev-middleware/lib/context.js:76:7)
    at context.compiler.plugin (/asdf/node_modules/webpack-dev-middleware/lib/context.js:116:5)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/asdf/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/asdf/node_modules/webpack/node_modules/tapable/lib/Hook.js:35:21)
    at Watching._go (/asdf/node_modules/webpack/lib/Watching.js:40:32)
    at Watching.compiler.readRecords.err (/asdf/node_modules/webpack/lib/Watching.js:32:9)
error An unexpected error occurred: "Command failed.
Exit code: 1
```

**Comment by arthurbergmz** [comment]
Have updated Webpack and html-webpack-plugin?

**Comment by fernandopasik** [comment]
I'm not using html-webpack-plugin

**Comment by arthurbergmz** [comment]
@fernandopasik 

Please, update to **v3.6.1**.
Thanks!

**Comment by fernandopasik** [comment]
Thank you @arthurbergmz it works great now!
