### ISSUE TITLE
Build Error: Cannot read property 'Symbol(Symbol.iterator)' of null

### ISSUE THREAD

**Issue by hitchcott** [arthurbergmz/webpack-pwa-manifest#7]
Hi, this is working for me with version 2.7, but breaks when using version 3:

```
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of null
    at Compiler.<anonymous> (/Users/chris/code/xxx/node_modules/webpack-pwa-manifest/dist/WebpackPwaManifest.js:71:51)
    at next (/Users/chris/code/xxx/node_modules/tapable/lib/Tapable.js:140:14)
    at /Users/chris/code/xxx/node_modules/optimize-css-assets-webpack-plugin/index.js:97:27
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
```

**Comment by hitchcott** [comment]
It was caused by plugin order; fixed in #8
